package:
  name: intakebuilder
  version: 0.0.0

source:
  #git_url: https://github.com/aradhakrishnanGFDL/CatalogBuilder.git
  path: .

build:
      script: "{{ PYTHON }} -m pip install . -vv"
      number: 0
      noarch: python

requirements:
  host: 
    - python
    - pip 
  run:
    - python
    - click
    - pandas
    - xarray
    - pytest
    - 'intake-esm>=2023.7.7'
test:
  imports:
    - intakebuilder 

about:
  home:
