# This is a basic workflow to help you get started with Actions

name: CI use difrnt repo directory

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ actiontest ]
  pull_request:
    branches: [ actiontest ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run:
    name: Add a text file
    runs-on: ubuntu-latest

    steps:
     - name: gen_intake_s3.py
        - run
          $CONDA/envs/intake/bin/pytest 
          $CONDA/envs/intake/bin/python3 gen_intake_s3.py
      # If you need to, you can check out your repo to a different location
     - name: addfiletorepo
        - uses: actions/checkout@v2
         with:
            path: './pathToRepo/'

       # You can make whatever type of change to the repo...
        - run: echo "123" > ./pathToRepo/file.txt

       # ...and then use the action as you would normally do, but providing the path to the repo
        - uses: EndBug/add-and-commit@v7
          with:
           message: 'Add the very useful text file'
           add: '*.txt --force'
           cwd: './pathToRepo/'

