name: Docker Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag aparnadotnoaa/catalogbuilder:latest
    - uses: addnab/docker-run-action@v3
      with:
        image: catalogbuilder:latest
        run: "conda activate catalogbuilder"
