name: Docker Image CI

on:
  push:
    branches: [ actionstest ]
  pull_request:
    branches: [ actionstest ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: aradhakrishnan/CatalogyBuilder@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
