name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        $CONDA/bin/conda --version
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda create -n intake
        $CONDA/bin/conda install -n intake -c conda-forge pandas xarray botocore boto3 pytest
    - name: tests_prelim
      run: |
        $CONDA/bin/pytest pytest
